version: "3.8"
services:

  mongo:
    image: mongo
    container_name: player_database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - player_database_volume:/data/db

volumes:
  player_database_volume: {}